---
name: Monthly tests.

on:
  # 2am of the 15th:
  schedule:
    - cron: "0 2 15 * *"

jobs:
  validate-video-urls:
    # Check if music video URLs in List.md are valid:
    uses: ./.github/workflows/validate_video_urls.yml
    secrets: inherit

  rvcgs-website-is-available:
    uses: jtalk/url-health-check-action@v3
    with:
      url: |
        https://www.randomvideoclipgenerator.com
        https://randomvideoclipgenerator.com
        http://www.randomvideoclipgenerator.com
        http://randomvideoclipgenerator.com

