---
name: Monthly tests.

on:
  # 2am of the 15th:
  schedule:
    - cron: "0 2 15 * *"

jobs:
  call-ci:
    # Check if music video URLs are valid.
    uses: ./.github/workflows/ci.yml
    secrets: inherit

  website-is-available:
    uses: jtalk/url-health-check-action@v3
    with:
      url: https://www.randomvideoclipgenerator.com|https://randomvideoclipgenerator.com|http://www.randomvideoclipgenerator.com|http://randomvideoclipgenerator.com
