---
# Python code only.
# Quality: lint, type-checking, import order.
# Dependency audit.
# Testing: unit, coverage, integration.
name: Python-CICD

on:
  workflow_run:
    workflows:
      - Meta-Code-Quality
    types:
      - completed

env:
  # Specify minimum code coverage for Unit Testing:
  TARGET_COVERAGE: 0
  SUBFOLDER_NAME: 'PythonCore'
  SCRIPT_NAME: 'random_video_clip_generator.py'

jobs:
  # Auxiliary job that checks if any Python file changed.
  any-python-changed:
    #if: always()
    # Skip job if upstream workflow meta-code quality failed:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    outputs:
      any_python_files_changed:
        ${{ steps.python_was_updated.outputs.any_changed }}
    steps:
      # Fetch all history for version tagging:
      - uses: ./.github/actions/CheckoutMyCode
        with:
          deep: true
      - id: python_was_updated
        uses: ./.github/actions/ChangedFiles
        with:
          files: "**/*.py"
      - run: |
          echo 'Did any Python file(s) change in this commit: '
          echo ${{ steps.python_was_updated.outputs.any_changed }}

  # TMP: SKIPPING!
  python-code-quality:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-versions: ['3.10']
    timeout-minutes: 9
    if: false
    # Skip job if meta-code quality failed:
    #if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
      - uses: ./.github/actions/CheckoutMyCode

      - name: Setup Python ${{ matrix.python-versions }}.
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-versions }}

      - name: Install dependencies.
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Lint Python code.
        env:
          PYTHONPATH: .
        run: |
          echo 'Files to be linted: '
          files=$(git ls-files '*.py')
          echo $files
          pylint -v $files

      - name: Type checking.
        run: |
          echo 'Files to be type-checked: '
          files=$(git ls-files '*.py')
          echo $files
          mypy $files

      - name: Import ordering.
        run: |
          isort --check --verbose .

      - name: Dependency audit.
        run: |
          pyscan

  # TMP: SKIPPING!
  # Runs on Windows: unit + code coverage, integration.
  code-testing:
    needs: python-code-quality
    # Removed functionality: skip-tests as that causes
    # even indirectly dependent jobs (like Release) to
    # also be skipped!
    if: false
    # Skip job if meta-code quality failed:
    #if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: windows-latest
    strategy:
      matrix:
        python-versions: ['3.10']
    timeout-minutes: 13

    steps:
      - uses: ./.github/actions/CheckoutMyCode

      - name: Install FFMpeg, VLC.
        run: |
          choco install ffmpeg -y
          choco install vlc -y

      # PowerShell requires call operator (&) to exec quoted paths:
      - name: Verify VLC installation.
        run: >
          & "C:\Program Files\VideoLAN\VLC\vlc-cache-gen.exe" --version

      - name: Setup Python ${{ matrix.python-versions }}.
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-versions }}

      - name: Install dependencies.
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Setup, create fake example videos.
        env:
          PYTHONPATH: .
        run: |
          python tests/setup.py

      - name: Unit testing.
        env:
          PYTHONPATH: .
        run: |
          pytest -vvv tests/unit_tests.py

      - name: Code coverage.
        env:
          PYTHONPATH: .
        run: >
          pytest --cov=${{ env.SUBFOLDER_NAME }}
          --cov-fail-under=${{ env.TARGET_COVERAGE }}
          tests/unit_tests.py

      - name: Integration testing.
        env:
          PYTHONPATH: .
        run: pytest -vvv tests/integration_tests.py

  # TMP: SKIPPING!
  # Auxiliary job that checks if core Python script changed.
  core-changed:
    needs: code-testing #XXX
    # Run even if code testing was skipped:
    #if: always()
    if: false
    # Skip job if meta-code quality failed:
    #if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    outputs:
      core_python_script_changed:
        ${{ steps.script_was_updated.outputs.any_changed }}
    steps:
      # Fetch all history for version tagging:
      - uses: ./.github/actions/CheckoutMyCode
        with:
          deep: true
      - id: script_was_updated
        uses: ./.github/actions/ChangedFiles
        with:
          files: ${{ env.SUBFOLDER_NAME }}/${{ env.SCRIPT_NAME }}
      - run: |
          echo 'Did PythonCore script change in this commit: '
          echo ${{ steps.script_was_updated.outputs.any_changed }}

  # TMP: SKIPPING!
  # Conventional Commits Release (PSR: Python Semantic Release).
  release:
    needs: [core-changed, code-testing]
    if: false
    # MUST specify if always if any upstream jobs are skipped:
    #if: always()
    #if: >-
    #  github.ref == 'refs/heads/main' &&
    #  needs.core-changed.outputs.core-python-script-changed == 'true'
    # Skip job if meta-code quality failed:
    #if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    # Allow commits, tags, pushes:
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      - name: Setup Python.
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Python Semantic Release.
        run: |
          python -m pip install --upgrade pip
          python -m pip install python-semantic-release

      - name: Configure Git.
        run: |
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'

      - name: Semantic Release.
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Locally do: python -m semantic_release
          semantic-release --verbose --strict --noop --version
          # Bump version, commit, tag, publish GitHub Release:
          semantic-release --verbose --strict --config pyproject.toml \
            version --skip-build --vcs-release

  # TMP: SKIPPING!
  # Upload Python script to S3 only when:
  #  * Main branch completes CI.
  #  * Script changed.
  deploy-to-s3:
    needs: [release, core-changed]
    if: false
    # Skip job if meta-code quality failed:
    #if: ${{ github.event.workflow_run.conclusion == 'success' }}
    #if: always()
    #if: >-
    #  github.ref == 'refs/heads/main' &&
    #  needs.core-changed.outputs.core-python-script-changed == 'true'
    runs-on: ubuntu-latest
    env:
      BUCKET: 'rvcg-marq-30072025'
      REGION: 'us-east-2'
      VERIFY_BASH_SCRIPT: '.github/scripts/verify_deployed_version.sh'

    steps:
      - name: Checkout code (deep).
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: main

      - name: Pull release.
        run: git pull origin main

      - name: Setup Python.
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      # No need to install AWS CLI.
      # These are needed or import breaks.
      - name: Install boto3.
        run: |
          python -m pip install --upgrade pip
          python -m pip install boto3 boto3-stubs boto3-stubs[s3]

      - name: Load AWS credentials from GitHub secrets.
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID_DEPLOY2S3LAMBDA }}
          aws-secret-access-key: >-
            ${{ secrets.AWS_SECRET_ACCESS_KEY_DEPLOY2S3LAMBDA }}
          aws-region: ${{ env.REGION }}

      - name: Verify AWS CLI is available.
        run: |
          which aws
          aws --version

      - name: Upload script to S3.
        run: >
          aws s3 cp ${{ env.SUBFOLDER_NAME }}/${{ env.SCRIPT_NAME }}
          s3://${{ env.BUCKET }}/${{ env.SCRIPT_NAME }}
          --content-type 'text/x-python'
          --content-disposition "attachment; filename=${{ env.SCRIPT_NAME }}"
          --metadata-directive REPLACE

      - name: Verify correct version is live.
        run: |
          chmod +x ${{ env.VERIFY_BASH_SCRIPT }}
          ${{ env.VERIFY_BASH_SCRIPT }} \
            "${{ env.SUBFOLDER_NAME }}" \
            "${{ env.SCRIPT_NAME }}" \
            "${{ env.BUCKET }}"

  # TMP: SKIPPING!
  deploy-to-lambda:
    needs: [deploy-to-s3, core-changed]
    if: false
    # Skip job if meta-code quality failed:
    #if: ${{ github.event.workflow_run.conclusion == 'success' }}
    #if: always()
    #if: >-
    #  github.ref == 'refs/heads/main' &&
    #  needs.core-changed.outputs.core-python-script-changed == 'true'
    runs-on: ubuntu-latest
    env:
      REGION: 'us-east-2'
      BUCKET: 'rvcg-marq-30072025'
      LAMBDA_FUNCTION_NAME: 'generate_xml_playlist_lambda'

    steps:
      - name: Checkout code (deep).
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: main

      - name: Pull Release.
        run: git pull origin main

      - name: Load AWS credentials from GitHub secrets.
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID_DEPLOY2S3LAMBDA }}
          aws-secret-access-key: >-
            ${{ secrets.AWS_SECRET_ACCESS_KEY_DEPLOY2S3LAMBDA }}
          aws-region: ${{ env.REGION }}

      - name: Deploy to Lambda.
        run: |
          script="${{ env.SUBFOLDER_NAME }}/${{ env.SCRIPT_NAME }}"
          zipfile=packaged.zip
          zip -v $zipfile $script
          ls -ltrA
          aws lambda update-function-code \
          --function-name ${{ env.LAMBDA_FUNCTION_NAME }} \
          --zip-file fileb://$zipfile
