---
# Send myself a notification on Discord
#   if any of the YouTube music video URLs is unavailable.
name: Validate music video URLs.

on:
  pull_request:
    paths:
      - "List.md"
  push:
    paths:
      - "List.md"
  workflow_dispatch:  # Allow manual execution.
  # Run every Friday at 2am CST:
  schedule:
    - cron: '0 8 * * 5'

jobs:
  check-youtube-music-videos-listed-links:
    runs-on: ubuntu-latest
    env:
      GOOGLEAPIYOUTUBEKEY: ${{ secrets.GOOGLEAPIYOUTUBEKEY }}
      SEND_NOTIFICATION_SCRIPT: '.github/scripts/send_notification.sh'
    timeout-minutes: 20
    strategy:
      matrix:
        python-versions: ['3.10']
    steps:
      - name: Checkout code.
        uses: actions/checkout@v4

      - name: Setup Python ${{ matrix.python-versions }}.
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-versions }}

      - name: Install dependencies.
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Verify URLs are valid and videos exist using Pytest.
        id: health_check
        continue-on-error: true
        run: |
          PYTHONPATH=. pytest -vvv tests/test_videos_exist.py

      - name: Send notification on failure.
        if: steps.health_check.outcome == 'failure'
        run: |
          chmod +x ${{ env.SEND_NOTIFICATION_SCRIPT }}
          ${{ env.SEND_NOTIFICATION_SCRIPT }} \
            "${{ steps.health_check.outputs.failed_urls }}" \
            "${{ secrets.DISCORD_WEBHOOK_URL }}" \
            'Music video(s) not found alert.' \
            'Music video list health check failed.'
