---
name: Web-CICD

on: push

env:
  SUBFOLDER_NAME: 'CloudService'
  CSS_STYLESHEET: 'styles.css'

jobs:
  # Auxiliary job that checks if CSS stylesheet changed.
  css-changed:
    runs-on: ubuntu-latest
    outputs:
      css_stylesheet_changed:
        ${{ steps.css_was_updated.outputs.any_changed }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - id: css_was_updated
        uses: tj-actions/changed-files@v45
        with:
          files: ${{ env.SUBFOLDER_NAME }}/${{ env.CSS_STYLESHEET }}

  # Auxiliary job that checks if any HTML documents changed.
  any-html-changed:
    runs-on: ubuntu-latest
    outputs:
      html_document_changed:
        ${{ steps.any_html_document_was_updated.outputs.any_changed }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - id: any_html_document_was_updated
        uses: tj-actions/changed-files@v45
        with:
          files: |
            **/*.html

  # Auxiliary job that checks if any JavaScript scripts changed.
  any-js-changed:
    runs-on: ubuntu-latest
    outputs:
      js-script-changed:
        ${{ steps.any_js_script_was_updated.outputs.any_changed }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - id: any_js_script_was_updated
        uses: tj-actions/changed-files@v45
        with:
          files: |
            **/*.js

  # Lint CSS stylesheet only if it changed in this commit (main branch).
  css-lint:
    needs: css-changed
    if: >-
      github.ref == 'refs/heads/main' &&
      needs.css-changed.outputs.css_stylesheet_changed == 'true'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js.
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Lint CSS.
        run: |
          npm install --global stylelint stylelint-config-standard
          npm list -g --depth=0
          npx stylelint --version
          npx stylelint CloudService/styles.css

  # Lint any HTML documents that changed in this commit (main branch).
  html-lint:
    needs: any-html-changed
    if: >-
      github.ref == 'refs/heads/main' &&
      needs.any-html-changed.outputs.html_document_changed == 'true'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js.
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Lint HTML.
        run: |
          npm install --global html-validate
          npm list -g --depth=0
          html-validate --version
          html-validate .

  # Lint any JavaScript scripts that changed in this commit (main branch).
  js-lint:
    needs: any-js-changed
    if: >-
      github.ref == 'refs/heads/main' &&
      needs.any-js-changed.outputs.js-script-changed == 'true'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js.
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Lint JavaScript.
        run: |
          npm install --global standard
          npm list -g --depth=0
          npx standard --version
          npx standard
